/*
Marketing Touchpoints Fact Table

Grain: one row per customer-campaign-channel touchpoint (marketing_touchpoint_id).

Dimension joins:
- customer_key    → dim_customer             (via customer_id)
- campaign_key    → dim_marketing_campaigns  (composite join: campaign_name + channel)
- campaign_date_key → dim_date

clicked and converted are binary measures (0 or 1).
Sum them to count total clicks and conversions.
Divide to compute click-through rate (converted / clicked) or
conversion rate (converted / total touchpoints).

Ghost customer touchpoints are included and flagged — these represent interactions
from customer IDs not found in the customer master.
*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.fact_marketing_touchpoints;

CREATE TABLE mart.fact_marketing_touchpoints (
    fact_touchpoint_key           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Degenerate dimension (business key)
    marketing_touchpoint_id       TEXT NOT NULL,

    -- Foreign keys
    customer_key                  INT  NOT NULL REFERENCES mart.dim_customer(customer_key),
    campaign_key                  INT  NOT NULL REFERENCES mart.dim_marketing_campaigns(campaign_key),
    campaign_date_key             INT  REFERENCES mart.dim_date(date_key),

    -- Measures (binary flags: 0 = no, 1 = yes)
    clicked                       SMALLINT,
    converted                     SMALLINT,

    -- Data quality flags
    ghost_customer_flag           BOOLEAN DEFAULT FALSE,
    converted_without_click_flag  BOOLEAN DEFAULT FALSE,

    created_at                    TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO mart.fact_marketing_touchpoints (
    marketing_touchpoint_id,
    customer_key,
    campaign_key,
    campaign_date_key,
    clicked,
    converted,
    ghost_customer_flag,
    converted_without_click_flag
)
SELECT
    mc.marketing_touchpoint_id,
    COALESCE(dc.customer_key,  -1)                   AS customer_key,
    COALESCE(dmc.campaign_key, -1)                   AS campaign_key,
    TO_CHAR(mc.campaign_date, 'YYYYMMDD')::INT       AS campaign_date_key,
    mc.clicked,
    mc.converted,
    COALESCE(mc.ghost_customer_flag,          FALSE) AS ghost_customer_flag,
    COALESCE(mc.converted_without_click_flag, FALSE) AS converted_without_click_flag
FROM stg.stg_marketing_campaigns         mc
LEFT JOIN mart.dim_customer              dc   ON mc.customer_id   = dc.customer_id
LEFT JOIN mart.dim_marketing_campaigns   dmc  ON mc.campaign_name = dmc.campaign_name
                                             AND mc.channel       = dmc.channel
WHERE mc.marketing_touchpoint_id IS NOT NULL;