/*
Payments Fact Table

Grain: one row per payment (payment_id).

Dimension joins:
- payment_key      → dim_payment    (payment_method, payment_status, payment_date)
- customer_key     → dim_customer   (customer_id is on the order, not the payment)
- payment_date_key → dim_date

Order-level context (order_status, sales_channel) is denormalized
from stg_orders to support slicing payment revenue by channel
without joining back through the order layer. order_status reflects the value
at order creation only; no status history is tracked (see model_documentation.md
section 4.1).

country is intentionally NOT included here. raw_orders.country is assigned
independently at random per order and carries no real geographic signal —
see fact_order_items.sql for the proof. Use dim_customer.country (via
customer_key) for any country-based analysis instead.

payment_amount is the single measure. Use payment_status from dim_payment
to filter for 'Paid' rows only when calculating realized revenue.
*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.fact_payments;

CREATE TABLE mart.fact_payments (
    fact_payment_key             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Degenerate dimensions (business keys)
    payment_id                   TEXT NOT NULL,
    order_id                     TEXT,

    -- Foreign keys
    customer_key                 INT  NOT NULL REFERENCES mart.dim_customer(customer_key),
    payment_key                  INT  NOT NULL REFERENCES mart.dim_payment(payment_key),
    payment_date_key             INT  REFERENCES mart.dim_date(date_key),

    -- Order-level context
    order_status                 TEXT,
    sales_channel                TEXT,

    -- Measures
    payment_amount               NUMERIC(12, 2),

    -- Data quality flags
    ghost_order_flag             BOOLEAN DEFAULT FALSE,

    created_at                   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO mart.fact_payments (
    payment_id,
    order_id,
    customer_key,
    payment_key,
    payment_date_key,
    order_status,
    sales_channel,
    payment_amount,
    ghost_order_flag
)
SELECT
    p.payment_id,
    p.order_id,
    COALESCE(dc.customer_key, -1)                  AS customer_key,
    COALESCE(dp.payment_key,  -1)                  AS payment_key,
    TO_CHAR(p.payment_date, 'YYYYMMDD')::INT       AS payment_date_key,
    COALESCE(o.order_status,  'Unknown')           AS order_status,
    COALESCE(o.sales_channel, 'Unknown')           AS sales_channel,
    p.payment_amount,
    COALESCE(p.ghost_order_flag, FALSE) AS ghost_order_flag
FROM stg.stg_payments            p
LEFT JOIN stg.stg_orders         o   ON p.order_id    = o.order_id
LEFT JOIN mart.dim_customer      dc  ON o.customer_id = dc.customer_id
LEFT JOIN mart.dim_payment       dp  ON p.payment_id  = dp.payment_id
WHERE p.payment_id IS NOT NULL;