/*
Order Items Fact Table

Grain: one row per order line item (order_item_id).

Dimension joins:
- customer_key    → dim_customer  (customer_id lives on the order, not the line item)
- product_key     → dim_product
- order_date_key  → dim_date

Order-level attributes (order_status, sales_channel, shipping_method)
are denormalized onto the fact to avoid an extra join on every query.
order_id is kept as a degenerate dimension so fact_payments and fact_returns
can be joined back to line items without a separate dim_order table.

country is intentionally NOT included here. raw_orders.country is assigned
independently at random per order (proven: distinct-country-count per customer
matches the expected value for uniform random draws with replacement) and is
89.9% inconsistent with the same customer's dim_customer.country. It carries
no real geographic signal. Use dim_customer.country (via customer_key) for any
country-based analysis instead.

Ghost products are included and flagged — exclude ghost_product_flag = TRUE
for clean revenue and margin reporting.

quantity is sourced from stg_order_items.quantity_capped, not quantity_raw/quantity.
228 rows had a corrupted quantity (>99, up to 1996) in the raw data; quantity_capped
back-solves the real value from line_total_original — see stg_order_items.sql.
*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.fact_order_items;

CREATE TABLE mart.fact_order_items (
    fact_order_item_key       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Degenerate dimensions (business keys)
    order_item_id             TEXT NOT NULL,
    order_id                  TEXT NOT NULL,

    -- Foreign keys
    customer_key              INT  NOT NULL REFERENCES mart.dim_customer(customer_key),
    product_key               INT  NOT NULL REFERENCES mart.dim_product(product_key),
    order_date_key            INT  REFERENCES mart.dim_date(date_key),

    -- Order-level attributes (same value for every line item on the same order)
    order_status              TEXT,
    sales_channel             TEXT,
    shipping_method           TEXT,

    -- Measures
    quantity                  INT,
    unit_price                NUMERIC(10, 2),
    discount                  NUMERIC(10, 4),
    line_total                NUMERIC(12, 2),

    -- Data quality flags
    ghost_product_flag        BOOLEAN DEFAULT FALSE,
    zero_unit_price_flag      BOOLEAN DEFAULT FALSE,
    line_total_mismatch_flag  BOOLEAN DEFAULT FALSE,

    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO mart.fact_order_items (
    order_item_id,
    order_id,
    customer_key,
    product_key,
    order_date_key,
    order_status,
    sales_channel,
    shipping_method,
    quantity,
    unit_price,
    discount,
    line_total,
    ghost_product_flag,
    zero_unit_price_flag,
    line_total_mismatch_flag
)
SELECT
    oi.order_item_id,
    oi.order_id,
    COALESCE(dc.customer_key, -1)                    AS customer_key,
    COALESCE(dp.product_key,  -1)                    AS product_key,
    TO_CHAR(o.order_date, 'YYYYMMDD')::INT           AS order_date_key,
    COALESCE(o.order_status,    'Unknown')           AS order_status,
    COALESCE(o.sales_channel,   'Unknown')           AS sales_channel,
    COALESCE(o.shipping_method, 'Unknown')           AS shipping_method,
    oi.quantity_capped                               AS quantity,
    oi.unit_price,
    oi.discount,
    oi.line_total_clean                              AS line_total,
    COALESCE(oi.ghost_product_flag,       FALSE)     AS ghost_product_flag,
    COALESCE(oi.zero_unit_price_flag,     FALSE)     AS zero_unit_price_flag,
    COALESCE(oi.line_total_mismatch_flag, FALSE)     AS line_total_mismatch_flag
FROM stg.stg_order_items         oi
LEFT JOIN stg.stg_orders          o  ON oi.order_id  = o.order_id
LEFT JOIN mart.dim_customer       dc ON o.customer_id = dc.customer_id
LEFT JOIN mart.dim_product        dp ON oi.product_id = dp.product_id
WHERE oi.order_item_id IS NOT NULL;