/*
Returns Fact Table

Grain: one row per return (return_id).

Dimension joins:
- customer_key      → dim_customer      (customer_id is on the order, not the return)
- product_key       → dim_product
- return_reason_key → dim_return_reason (text-based join on return_reason value)
- return_date_key   → dim_date

Order-level context (order_status, sales_channel) is denormalized from
stg_orders to enable return rate analysis by channel. order_status
reflects the value at order creation only; no status history is tracked (see
model_documentation.md section 4.1).

country is intentionally NOT included here. raw_orders.country is assigned
independently at random per order and carries no real geographic signal —
see fact_order_items.sql for the proof. Use dim_customer.country (via
customer_key) for any country-based analysis instead.

return_reason_key is nullable: dim_return_reason has no -1 fallback row because
all return reasons from staging are mapped inline. If a reason somehow has no match,
the FK is NULL rather than causing an insert failure.

Ghost records are included and flagged — exclude ghost_product_flag = TRUE and
ghost_order_flag = TRUE for clean return rate reporting.
*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.fact_returns;

CREATE TABLE mart.fact_returns (
    fact_return_key           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Degenerate dimensions (business keys)
    return_id                 TEXT NOT NULL,
    order_id                  TEXT,

    -- Foreign keys
    customer_key              INT  NOT NULL REFERENCES mart.dim_customer(customer_key),
    product_key               INT  NOT NULL REFERENCES mart.dim_product(product_key),
    return_reason_key         INT  REFERENCES mart.dim_return_reason(return_reason_key),
    return_date_key           INT  REFERENCES mart.dim_date(date_key),

    -- Order-level context
    order_status              TEXT,
    sales_channel             TEXT,

    -- Measures
    refund_amount             NUMERIC(12, 2),

    -- Data quality flags
    ghost_product_flag        BOOLEAN DEFAULT FALSE,
    ghost_order_flag          BOOLEAN DEFAULT FALSE,

    created_at                TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO mart.fact_returns (
    return_id,
    order_id,
    customer_key,
    product_key,
    return_reason_key,
    return_date_key,
    order_status,
    sales_channel,
    refund_amount,
    ghost_product_flag,
    ghost_order_flag
)
SELECT
    r.return_id,
    r.order_id,
    COALESCE(dc.customer_key,  -1)                  AS customer_key,
    COALESCE(dp.product_key,   -1)                  AS product_key,
    drr.return_reason_key,
    TO_CHAR(r.return_date, 'YYYYMMDD')::INT         AS return_date_key,
    COALESCE(o.order_status,   'Unknown')           AS order_status,
    COALESCE(o.sales_channel,  'Unknown')           AS sales_channel,
    r.refund_amount,
    COALESCE(r.ghost_product_flag, FALSE)                        AS ghost_product_flag,
    CASE WHEN o.order_id IS NULL THEN TRUE
         ELSE COALESCE(r.ghost_order_flag, FALSE) END            AS ghost_order_flag
FROM stg.stg_returns                  r
LEFT JOIN stg.stg_orders              o    ON r.order_id      = o.order_id
LEFT JOIN mart.dim_customer           dc   ON o.customer_id   = dc.customer_id
LEFT JOIN mart.dim_product            dp   ON r.product_id    = dp.product_id
LEFT JOIN mart.dim_return_reason      drr  ON r.return_reason = drr.return_reason
WHERE r.return_id IS NOT NULL;