/* 3. create dim_order table*/

DROP TABLE IF EXISTS mart.didm_order

--Create dim_order

DROP TABLE IF EXISTS mart.dim_order;

CREATE TABLE mart.dim_order (
    order_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id TEXT NOT NULL UNIQUE,

    order_date DATE,
    order_year INT,
    order_month INT,
    order_quarter INT,

    order_status TEXT,
    country TEXT,
    sales_channel TEXT,
    shipping_method TEXT
);
INSERT INTO mart.dim_order (
    order_key,
    order_id,
    order_date,
    order_year,
    order_month,
    order_quarter,
    order_status,
    country,
    sales_channel,
    shipping_method
)
VALUES (
    -1,
    'UNKNOWN',
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    'Unknown',
    'Unknown',
    'Unknown'
);
INSERT INTO mart.dim_order (
    order_id,
    order_date,
    order_year,
    order_month,
    order_quarter,
    order_status,
    country,
    sales_channel,
    shipping_method
)
SELECT
    order_id,
    order_date,
    order_year,
    order_month,
    order_quarter,

    COALESCE(order_status, 'Unknown') AS order_status,
    COALESCE(country, 'Unknown') AS country,
    COALESCE(sales_channel, 'Unknown') AS sales_channel,
    COALESCE(shipping_method, 'Unknown') AS shipping_method

FROM stg.stg_orders
WHERE order_id IS NOT NULL;