/* 5. create dim payment table
Duplicate payment_id check returned 0 rows.  
Each payment_id appears only once in the staging payment table.  
The UNIQUE constraint is still added to dim_payment to protect the dimension from future duplicate payment records.*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_payment CASCADE;

CREATE TABLE mart.dim_payment (
    payment_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_id TEXT NOT NULL,
    order_id TEXT,

    payment_method TEXT,
    payment_status TEXT,
    payment_date DATE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_payment_payment_id UNIQUE (payment_id) --Create a unique rule named uq_dim_payment_payment_id, and apply it to the column payment_id
);
INSERT INTO mart.dim_payment (
    payment_key,
    payment_id,
    order_id,
    payment_method,
    payment_status,
    payment_date
)
VALUES (
    -1,
    'UNKNOWN',
    NULL,
    'Unknown',
    'Unknown',
    NULL
)
ON CONFLICT (payment_id) DO NOTHING;

INSERT INTO mart.dim_payment (
    payment_id,
    order_id,
    payment_method,
    payment_status,
    payment_date
)
SELECT DISTINCT
    payment_id,
    order_id,
    payment_method,
    payment_status,
    payment_date
FROM stg.stg_payments
WHERE payment_id IS NOT NULL
ON CONFLICT (payment_id) DO NOTHING;
