CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_return_reason;

CREATE TABLE mart.dim_return_reason (
    return_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    return_reason TEXT NOT NULL,
    reason_category TEXT NOT NULL,

    CONSTRAINT uq_dim_return_reason UNIQUE (return_reason)
);
INSERT INTO mart.dim_return_reason (
    return_reason,
    reason_category
)

WITH cleaned_return_reasons AS (
    SELECT DISTINCT
        COALESCE(NULLIF(TRIM(return_reason), ''), 'Unknown') AS return_reason
    FROM stg.stg_returns
),

categorized_return_reasons AS (
    SELECT
        return_reason,

        CASE
    WHEN LOWER(return_reason) IN (
        'not provided',
        'unknown'
    )
        THEN 'Unknown'

    WHEN LOWER(return_reason) IN (
        'no longer needed',
        'changed mind'
    )
        THEN 'Customer preference'

    WHEN LOWER(return_reason) IN (
        'better price elsewhere'
    )
        THEN 'Price issue'

    WHEN LOWER(return_reason) IN (
        'not as described'
    )
        THEN 'Product information mismatch'

    WHEN LOWER(return_reason) IN (
        'poor quality'
    )
        THEN 'Product quality'

    WHEN LOWER(return_reason) IN (
        'damaged on arrival'
    )
        THEN 'Delivery issue'

    WHEN LOWER(return_reason) IN (
        'wrong item sent'
    )
        THEN 'Fulfillment issue'  --the customer did not receive the product they ordered

    WHEN LOWER(return_reason) IN (
        'duplicate order'
    )
        THEN 'Order issue'

    ELSE 'Other'
END AS reason_category

    FROM cleaned_return_reasons
)

SELECT
    return_reason,
    reason_category
FROM categorized_return_reasons

ON CONFLICT (return_reason) DO UPDATE
SET
    reason_category = EXCLUDED.reason_category; --if  category logic improves later, the table updates automatically.
