/* 2. Product Dimension Table

Creates one product row per cleaned product.
The surrogate key product_key is used for the star schema,
while product_id is kept as the original business key.
Product attributes and quality flags are stored for later analysis. */

DROP TABLE IF EXISTS mart.dim_product;

CREATE TABLE mart.dim_product (     --Create the dimension table
    product_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id TEXT UNIQUE NOT NULL,

    product_name TEXT,
    category TEXT,
    subcategory TEXT,
    brand TEXT,

    unit_cost NUMERIC(10,2),
    list_price NUMERIC(10,2),

    launch_date DATE,
    discontinued_flag BOOLEAN,

    price_issue_flag BOOLEAN,
    product_quality_status TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert the unknown product 

INSERT INTO mart.dim_product (
    product_key,
    product_id,
    product_name,
    category,
    subcategory,
    brand,
    unit_cost,
    list_price,
    launch_date,
    discontinued_flag,
    price_issue_flag,
    product_quality_status
)
VALUES (
    -1,
    'UNKNOWN',
    'Unknown product',
    'Unknown',
    'Unknown',
    'Unknown',
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    'Unknown product fallback'
);

--Insert real products

INSERT INTO mart.dim_product (
    product_id,
    product_name,
    category,
    subcategory,
    brand,
    unit_cost,
    list_price,
    launch_date,
    discontinued_flag,
    price_issue_flag,
    product_quality_status
)
SELECT
    product_id,

    COALESCE(product_name, 'Unknown product') AS product_name,
    COALESCE(category, 'Unknown') AS category,
    COALESCE(subcategory, 'Unknown') AS subcategory,
    COALESCE(brand, 'Unknown') AS brand,

    unit_cost,
    list_price,

    launch_date,
    discontinued_flag,

    COALESCE(price_issue_flag, FALSE) AS price_issue_flag,

    CASE
        WHEN product_id ILIKE '%ghost%' THEN 'Ghost product id'
        WHEN category IS NULL           THEN 'Missing category'
        ELSE 'Valid product'
    END AS product_quality_status

FROM stg.stg_products
WHERE product_id IS NOT NULL;