/*
Return Reason Dimension Table

One lookup row per unique return reason. Maps raw return reason text to a
standardized reason_category for grouping and reporting.

No unknown fallback row (-1) is needed here: NULL and blank reasons are mapped
to 'Unknown' inline during the INSERT, so every reason in fact_returns will
always find a match in this table.

ON CONFLICT DO UPDATE means the table self-corrects if reason_category logic
is improved and the script is re-run — without needing to DROP and recreate.
*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_return_reason CASCADE;

CREATE TABLE mart.dim_return_reason (
    return_reason_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    return_reason     TEXT NOT NULL,
    reason_category   TEXT NOT NULL,
    created_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_return_reason UNIQUE (return_reason)
);

INSERT INTO mart.dim_return_reason (
    return_reason,
    reason_category
)

WITH cleaned_return_reasons AS (
    SELECT DISTINCT
        COALESCE(NULLIF(TRIM(return_reason), ''), 'Unknown') AS return_reason
    FROM stg.stg_returns
),

categorized_return_reasons AS (
    SELECT
        return_reason,
        CASE
            WHEN LOWER(return_reason) IN ('not provided', 'unknown')
                THEN 'Unknown'
            WHEN LOWER(return_reason) IN ('no longer needed', 'changed mind')
                THEN 'Customer preference'
            WHEN LOWER(return_reason) IN ('better price elsewhere')
                THEN 'Price issue'
            WHEN LOWER(return_reason) IN ('not as described')
                THEN 'Product information mismatch'
            WHEN LOWER(return_reason) IN ('poor quality')
                THEN 'Product quality'
            WHEN LOWER(return_reason) IN ('damaged on arrival')
                THEN 'Delivery issue'
            WHEN LOWER(return_reason) IN ('wrong item sent')
                THEN 'Fulfillment issue'
            WHEN LOWER(return_reason) IN ('duplicate order')
                THEN 'Order issue'
            ELSE 'Other'
        END AS reason_category
    FROM cleaned_return_reasons
)

SELECT
    return_reason,
    reason_category
FROM categorized_return_reasons

ON CONFLICT (return_reason) DO UPDATE
SET reason_category = EXCLUDED.reason_category;