/*
Marketing Campaigns Dimension Table

One row per unique campaign_name + channel combination.
The source table is at the touchpoint grain (one row per customer interaction),
so DISTINCT is used to collapse it to the campaign-channel grain here.

Row -1 is the unknown fallback for touchpoints with no matching campaign.
*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_marketing_campaigns CASCADE;

CREATE TABLE mart.dim_marketing_campaigns (
    campaign_key  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    campaign_name TEXT NOT NULL,
    channel       TEXT NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_marketing_campaigns UNIQUE (campaign_name, channel)
);

-- Unknown fallback row
INSERT INTO mart.dim_marketing_campaigns (
    campaign_key,
    campaign_name,
    channel
)
VALUES (
    -1,
    'Unknown Campaign',
    'Unknown'
);

-- Insert real campaign-channel combinations
INSERT INTO mart.dim_marketing_campaigns (
    campaign_name,
    channel
)
SELECT DISTINCT  --only keep unique combinations
    COALESCE(campaign_name, 'Unknown Campaign') AS campaign_name,
    COALESCE(channel, 'Unknown') AS channel
FROM stg.stg_marketing_campaigns
ON CONFLICT (campaign_name, channel) DO NOTHING; --what should happen when a duplicate appears.
