/* 4. Create dim_marketing_campaigns Table
This table should use the real campaign grain: campaign_name + channel
The unique constraint protects the dimension table from duplicate campaign-channel rows.
The ON CONFLICT clause tells PostgreSQL to skip duplicate rows instead of stopping the insert with an error.*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_marketing_campaigns CASCADE;

CREATE TABLE mart.dim_marketing_campaigns (
    campaign_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- create surrogate key
    campaign_name TEXT NOT NULL,  --campaign_name must have a value
    channel TEXT NOT NULL, -- channel must have a value

    CONSTRAINT uq_dim_marketing_campaigns  --a constraint is a rule that protects table from bad or unwanted data.
        UNIQUE (campaign_name, channel) --defines what counts as duplicate.
);

-- Unknown fallback row
INSERT INTO mart.dim_marketing_campaigns (
    campaign_key,
    campaign_name,
    channel
)
VALUES (
    -1,
    'Unknown Campaign',
    'Unknown'
);

-- Insert real campaign-channel combinations
INSERT INTO mart.dim_marketing_campaigns (
    campaign_name,
    channel
)
SELECT DISTINCT  --only keep unique combinations
    COALESCE(campaign_name, 'Unknown Campaign') AS campaign_name,
    COALESCE(channel, 'Unknown') AS channel
FROM stg.stg_marketing_campaigns
ON CONFLICT (campaign_name, channel) DO NOTHING; --what should happen when a duplicate appears.
