/*
Payment Dimension Table

One row per unique payment_id. Stores payment method, status, and date.
order_id is NOT stored here — it belongs as a foreign key in fact_payments.

Row -1 is the unknown fallback for fact rows with no matching payment.
*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_payment CASCADE;

CREATE TABLE mart.dim_payment (
    payment_key    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_id     TEXT NOT NULL,
    payment_method TEXT,
    payment_status TEXT,
    payment_date   DATE,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_payment_payment_id UNIQUE (payment_id)
);

-- Unknown fallback row
INSERT INTO mart.dim_payment (
    payment_key,
    payment_id,
    payment_method,
    payment_status,
    payment_date
)
VALUES (
    -1,
    'UNKNOWN',
    'Unknown',
    'Unknown',
    NULL
)
ON CONFLICT (payment_id) DO NOTHING;

-- Real payments
INSERT INTO mart.dim_payment (
    payment_id,
    payment_method,
    payment_status,
    payment_date
)
SELECT DISTINCT
    payment_id,
    payment_method,
    payment_status,
    payment_date
FROM stg.stg_payments
WHERE payment_id IS NOT NULL
ON CONFLICT (payment_id) DO NOTHING;