/*
Customer Dimension Table

One row per unique customer_id. Provides customer demographics, geography,
registration info, and loyalty status for use in fact table joins.

Row -1 is the unknown fallback for fact rows with no matching customer.
*/

DROP TABLE IF EXISTS mart.dim_customer;

CREATE TABLE mart.dim_customer (
    customer_key  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   TEXT UNIQUE,

    full_name     TEXT,
    email         TEXT,
    phone         TEXT,

    country       TEXT,
    gender        TEXT,

    birth_year    INT,
    age_group     TEXT,

    registration_date DATE,
    registration_year INT,

    loyalty_member BOOLEAN,

    missing_email_flag             BOOLEAN,
    missing_phone_flag             BOOLEAN,
    missing_registration_date_flag BOOLEAN,

    is_unknown_customer BOOLEAN,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Unknown fallback row
INSERT INTO mart.dim_customer (
    customer_key,
    customer_id,
    full_name,
    email,
    phone,
    country,
    gender,
    birth_year,
    age_group,
    registration_date,
    registration_year,
    loyalty_member,
    missing_email_flag,
    missing_phone_flag,
    missing_registration_date_flag,
    is_unknown_customer
)
VALUES (
    -1,
    'UNKNOWN',
    'Unknown Customer',
    NULL,
    NULL,
    'Unknown',
    'Unknown',
    NULL,
    'Unknown',
    NULL,
    NULL,
    NULL,
    TRUE,
    TRUE,
    TRUE,
    TRUE
);

-- Real customers
INSERT INTO mart.dim_customer (
    customer_id,
    full_name,
    email,
    phone,
    country,
    gender,
    birth_year,
    age_group,
    registration_date,
    registration_year,
    loyalty_member,
    missing_email_flag,
    missing_phone_flag,
    missing_registration_date_flag,
    is_unknown_customer
)
SELECT
    customer_id,
    full_name,
    email,
    phone,
    COALESCE(country, 'Unknown') AS country,
    COALESCE(gender, 'Unknown')  AS gender,
    birth_year,
    CASE
        WHEN birth_year IS NULL               THEN 'Unknown'
        WHEN birth_year >= 2010               THEN 'Under 18'
        WHEN birth_year BETWEEN 1997 AND 2009 THEN '18-29'
        WHEN birth_year BETWEEN 1987 AND 1996 THEN '30-39'
        WHEN birth_year BETWEEN 1977 AND 1986 THEN '40-49'
        WHEN birth_year BETWEEN 1967 AND 1976 THEN '50-59'
        WHEN birth_year < 1967                THEN '60+'
        ELSE 'Unknown'
    END AS age_group,
    registration_date,
    EXTRACT(YEAR FROM registration_date)::INT AS registration_year,
    loyalty_member,
    email IS NULL             AS missing_email_flag,
    phone IS NULL             AS missing_phone_flag,
    registration_date IS NULL AS missing_registration_date_flag,
    FALSE                     AS is_unknown_customer
FROM stg.stg_customers
WHERE customer_id IS NOT NULL;