
/*
1. Customer Dimension Table

This step creates the customer dimension table for the star schema.
Each cleaned customer from stg.stg_customers is stored as one row in mart.dim_customer.

The generated customer_key is used as the surrogate key for joins with fact tables.
The original customer_id is kept as the business key from the source system.
*/

DROP TABLE IF EXISTS mart.dim_customer;

-- create the table structurre
CREATE TABLE mart.dim_customer (
    customer_key INT PRIMARY KEY,
    customer_id TEXT UNIQUE,

    full_name TEXT,
    email TEXT,
    phone TEXT,

    country TEXT,
    gender TEXT,

    birth_year INT,
    age_group TEXT,

    registration_date DATE,
    registration_year INT,

    loyalty_member BOOLEAN,

    missing_email_flag BOOLEAN,
    missing_phone_flag BOOLEAN,
    missing_registration_date_flag BOOLEAN,

    is_unknown_customer BOOLEAN
);

-- Insert the unknown customer row ,creates one artificial fallback customer.
INSERT INTO mart.dim_customer (
    customer_key,
    customer_id,
    full_name,
    email,
    phone,
    country,
    gender,
    birth_year,
    age_group,
    registration_date,
    registration_year,
    loyalty_member,
    missing_email_flag,
    missing_phone_flag,
    missing_registration_date_flag,
    is_unknown_customer
)
VALUES (
    -1,    --special surrogate key for unknown customer, means “we could not assign this fact row to a known customer”.
    'UNKNOWN',    --artificial business key
    'Unknown Customer',
    NULL, --no email known
    NULL, --no phone known
    'Unknown', --country unknown
    'Unknown',  --gender unknown
    NULL,       -- birth year unknown
    'Unknown',   --age group unknown
    NULL,        --registration date unknown
    NULL,        --registration year unknown
    NULL,      --loyalty status unknown
    TRUE,      -- email is missing
    TRUE,  --phone is missing
    TRUE,  --  registration data is missing
    TRUE --this is not a real customer
);

-- Insert real customers,loads all real customers from your cleaned customer table.

INSERT INTO mart.dim_customer (
    customer_key,
    customer_id,
    full_name,
    email,
    phone,
    country,
    gender,
    birth_year,
    age_group,
    registration_date,
    registration_year,
    loyalty_member,
    missing_email_flag,
    missing_phone_flag,
    missing_registration_date_flag,
    is_unknown_customer
)
SELECT
    ROW_NUMBER() OVER (ORDER BY customer_id) AS customer_key,

    customer_id,
    full_name,
    email,
    phone,

    COALESCE(country, 'Unknown') AS country,
    COALESCE(gender, 'Unknown') AS gender,

    birth_year,

    CASE
        WHEN birth_year IS NULL THEN 'Unknown'
        WHEN birth_year >= 2010 THEN 'Under 18'
        WHEN birth_year BETWEEN 1997 AND 2009 THEN '18-29'
        WHEN birth_year BETWEEN 1987 AND 1996 THEN '30-39'
        WHEN birth_year BETWEEN 1977 AND 1986 THEN '40-49'
        WHEN birth_year BETWEEN 1967 AND 1976 THEN '50-59'
        WHEN birth_year < 1967 THEN '60+'
        ELSE 'Unknown'
    END AS age_group,

    registration_date,

    EXTRACT(YEAR FROM registration_date)::INT AS registration_year,

    loyalty_member,

    CASE WHEN email IS NULL THEN TRUE ELSE FALSE END AS missing_email_flag,
    CASE WHEN phone IS NULL THEN TRUE ELSE FALSE END AS missing_phone_flag,
    CASE WHEN registration_date IS NULL THEN TRUE ELSE FALSE END AS missing_registration_date_flag,

    FALSE AS is_unknown_customer

FROM stg.stg_customers
WHERE customer_id IS NOT NULL;  --customers without customer_id should not become normal dimension rows.



/* 2. Product Dimension Table

Creates one product row per cleaned product.
The surrogate key product_key is used for the star schema,
while product_id is kept as the original business key.
Product attributes and quality flags are stored for later analysis. */

DROP TABLE IF EXISTS mart.dim_product;

CREATE TABLE mart.dim_product (     --Create the dimension table
    product_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    product_id TEXT UNIQUE NOT NULL,

    product_name TEXT,
    category TEXT,
    subcategory TEXT,
    brand TEXT,

    unit_cost NUMERIC(10,2),
    list_price NUMERIC(10,2),

    launch_date DATE,
    discontinued_flag BOOLEAN,

    price_issue_flag BOOLEAN,
    product_quality_status TEXT,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Insert the unknown product 

INSERT INTO mart.dim_product (
    product_key,
    product_id,
    product_name,
    category,
    subcategory,
    brand,
    unit_cost,
    list_price,
    launch_date,
    discontinued_flag,
    price_issue_flag,
    product_quality_status
)
VALUES (
    -1,
    'UNKNOWN',
    'Unknown product',
    'Unknown',
    'Unknown',
    'Unknown',
    NULL,
    NULL,
    NULL,
    NULL,
    TRUE,
    'Unknown product fallback'
);

--Insert real products

INSERT INTO mart.dim_product (
    product_id,
    product_name,
    category,
    subcategory,
    brand,
    unit_cost,
    list_price,
    launch_date,
    discontinued_flag,
    price_issue_flag,
    product_quality_status
)
SELECT
    product_id,

    COALESCE(product_name, 'Unknown product') AS product_name,
    COALESCE(category, 'Unknown') AS category,
    COALESCE(subcategory, 'Unknown') AS subcategory,
    COALESCE(brand, 'Unknown') AS brand,

    unit_cost,
    list_price,

    launch_date,
    discontinued_flag,

    COALESCE(price_issue_flag, FALSE) AS price_issue_flag,

    CASE
        WHEN product_id ILIKE '%ghost%' THEN 'Ghost product id' --ILIKE ignores uppercase/lowercase.
        WHEN category IS NULL THEN 'Missing category'
        ELSE 'Valid product'
    END AS product_quality_status -- i keept this column because is it good practice if we want to group by different quality issues. but this column is not necessary here .

FROM stg.stg_products
WHERE product_id IS NOT NULL;

/* 3. create dim_order table*/

DROP TABLE IF EXISTS mart.didm_order

--Create dim_order

DROP TABLE IF EXISTS mart.dim_order;

CREATE TABLE mart.dim_order (
    order_key INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    order_id TEXT NOT NULL UNIQUE,

    order_date DATE,
    order_year INT,
    order_month INT,
    order_quarter INT,

    order_status TEXT,
    country TEXT,
    sales_channel TEXT,
    shipping_method TEXT
);
INSERT INTO mart.dim_order (
    order_key,
    order_id,
    order_date,
    order_year,
    order_month,
    order_quarter,
    order_status,
    country,
    sales_channel,
    shipping_method
)
VALUES (
    -1,
    'UNKNOWN',
    NULL,
    NULL,
    NULL,
    NULL,
    'Unknown',
    'Unknown',
    'Unknown',
    'Unknown'
);
INSERT INTO mart.dim_order (
    order_id,
    order_date,
    order_year,
    order_month,
    order_quarter,
    order_status,
    country,
    sales_channel,
    shipping_method
)
SELECT
    order_id,
    order_date,
    order_year,
    order_month,
    order_quarter,

    COALESCE(order_status, 'Unknown') AS order_status,
    COALESCE(country, 'Unknown') AS country,
    COALESCE(sales_channel, 'Unknown') AS sales_channel,
    COALESCE(shipping_method, 'Unknown') AS shipping_method

FROM stg.stg_orders
WHERE order_id IS NOT NULL;

/* 4. Create dim_marketing_campaigns Table
This table should use the real campaign grain: campaign_name + channel
The unique constraint protects the dimension table from duplicate campaign-channel rows.
The ON CONFLICT clause tells PostgreSQL to skip duplicate rows instead of stopping the insert with an error.*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_marketing_campaigns CASCADE;

CREATE TABLE mart.dim_marketing_campaigns (
    campaign_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- create surrogate key
    campaign_name TEXT NOT NULL,  --campaign_name must have a value
    channel TEXT NOT NULL, -- channel must have a value

    CONSTRAINT uq_dim_marketing_campaigns  --a constraint is a rule that protects table from bad or unwanted data.
        UNIQUE (campaign_name, channel) --defines what counts as duplicate.
);

-- Unknown fallback row
INSERT INTO mart.dim_marketing_campaigns (
    campaign_key,
    campaign_name,
    channel
)
VALUES (
    -1,
    'Unknown Campaign',
    'Unknown'
);

-- Insert real campaign-channel combinations
INSERT INTO mart.dim_marketing_campaigns (
    campaign_name,
    channel
)
SELECT DISTINCT  --only keep unique combinations
    COALESCE(campaign_name, 'Unknown Campaign') AS campaign_name,
    COALESCE(channel, 'Unknown') AS channel
FROM stg.stg_marketing_campaigns
ON CONFLICT (campaign_name, channel) DO NOTHING; --what should happen when a duplicate appears.





/* 5. create dim payment table
Duplicate payment_id check returned 0 rows.  
Each payment_id appears only once in the staging payment table.  
The UNIQUE constraint is still added to dim_payment to protect the dimension from future duplicate payment records.*/

CREATE SCHEMA IF NOT EXISTS mart;

DROP TABLE IF EXISTS mart.dim_payment CASCADE;

CREATE TABLE mart.dim_payment (
    payment_key INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    payment_id TEXT NOT NULL,
    order_id TEXT,

    payment_method TEXT,
    payment_status TEXT,
    payment_date DATE,

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT uq_dim_payment_payment_id UNIQUE (payment_id) --Create a unique rule named uq_dim_payment_payment_id, and apply it to the column payment_id
);
INSERT INTO mart.dim_payment (
    payment_key,
    payment_id,
    order_id,
    payment_method,
    payment_status,
    payment_date
)
VALUES (
    -1,
    'UNKNOWN',
    NULL,
    'Unknown',
    'Unknown',
    NULL
)
ON CONFLICT (payment_id) DO NOTHING;

INSERT INTO mart.dim_payment (
    payment_id,
    order_id,
    payment_method,
    payment_status,
    payment_date
)
SELECT DISTINCT
    payment_id,
    order_id,
    payment_method,
    payment_status,
    payment_date
FROM stg.stg_payments
WHERE payment_id IS NOT NULL
ON CONFLICT (payment_id) DO NOTHING;


